# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_pares.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_pares.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12server_pares.proto\"2\n\x12RequisicaoInsercao\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\"\"\n\x10RespostaInsercao\x12\x0e\n\x06status\x18\x01 \x01(\x05\"#\n\x12RequisicaoConsulta\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"%\n\x10RespostaConsulta\x12\x11\n\tresultado\x18\x01 \x01(\t\"%\n\x12RequisicaoAtivacao\x12\x0f\n\x07servico\x18\x01 \x01(\t\"\"\n\x10RespostaAtivacao\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x13\n\x11RequisicaoTermino\"!\n\x0fRespostaTermino\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xdd\x01\n\x0bServerPares\x12\x32\n\x06Insere\x12\x13.RequisicaoInsercao\x1a\x11.RespostaInsercao\"\x00\x12\x34\n\x08\x43onsulta\x12\x13.RequisicaoConsulta\x1a\x11.RespostaConsulta\"\x00\x12\x31\n\x05\x41tiva\x12\x13.RequisicaoAtivacao\x1a\x11.RespostaAtivacao\"\x00\x12\x31\n\x07Termina\x12\x12.RequisicaoTermino\x1a\x10.RespostaTermino\"\x00\x62\x06proto3'
)




_REQUISICAOINSERCAO = _descriptor.Descriptor(
  name='RequisicaoInsercao',
  full_name='RequisicaoInsercao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='RequisicaoInsercao.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valor', full_name='RequisicaoInsercao.valor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=72,
)


_RESPOSTAINSERCAO = _descriptor.Descriptor(
  name='RespostaInsercao',
  full_name='RespostaInsercao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RespostaInsercao.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=108,
)


_REQUISICAOCONSULTA = _descriptor.Descriptor(
  name='RequisicaoConsulta',
  full_name='RequisicaoConsulta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='RequisicaoConsulta.chave', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=145,
)


_RESPOSTACONSULTA = _descriptor.Descriptor(
  name='RespostaConsulta',
  full_name='RespostaConsulta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultado', full_name='RespostaConsulta.resultado', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=184,
)


_REQUISICAOATIVACAO = _descriptor.Descriptor(
  name='RequisicaoAtivacao',
  full_name='RequisicaoAtivacao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='servico', full_name='RequisicaoAtivacao.servico', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=223,
)


_RESPOSTAATIVACAO = _descriptor.Descriptor(
  name='RespostaAtivacao',
  full_name='RespostaAtivacao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RespostaAtivacao.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=259,
)


_REQUISICAOTERMINO = _descriptor.Descriptor(
  name='RequisicaoTermino',
  full_name='RequisicaoTermino',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=280,
)


_RESPOSTATERMINO = _descriptor.Descriptor(
  name='RespostaTermino',
  full_name='RespostaTermino',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RespostaTermino.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=315,
)

DESCRIPTOR.message_types_by_name['RequisicaoInsercao'] = _REQUISICAOINSERCAO
DESCRIPTOR.message_types_by_name['RespostaInsercao'] = _RESPOSTAINSERCAO
DESCRIPTOR.message_types_by_name['RequisicaoConsulta'] = _REQUISICAOCONSULTA
DESCRIPTOR.message_types_by_name['RespostaConsulta'] = _RESPOSTACONSULTA
DESCRIPTOR.message_types_by_name['RequisicaoAtivacao'] = _REQUISICAOATIVACAO
DESCRIPTOR.message_types_by_name['RespostaAtivacao'] = _RESPOSTAATIVACAO
DESCRIPTOR.message_types_by_name['RequisicaoTermino'] = _REQUISICAOTERMINO
DESCRIPTOR.message_types_by_name['RespostaTermino'] = _RESPOSTATERMINO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequisicaoInsercao = _reflection.GeneratedProtocolMessageType('RequisicaoInsercao', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOINSERCAO,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RequisicaoInsercao)
  })
_sym_db.RegisterMessage(RequisicaoInsercao)

RespostaInsercao = _reflection.GeneratedProtocolMessageType('RespostaInsercao', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTAINSERCAO,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RespostaInsercao)
  })
_sym_db.RegisterMessage(RespostaInsercao)

RequisicaoConsulta = _reflection.GeneratedProtocolMessageType('RequisicaoConsulta', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOCONSULTA,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RequisicaoConsulta)
  })
_sym_db.RegisterMessage(RequisicaoConsulta)

RespostaConsulta = _reflection.GeneratedProtocolMessageType('RespostaConsulta', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTACONSULTA,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RespostaConsulta)
  })
_sym_db.RegisterMessage(RespostaConsulta)

RequisicaoAtivacao = _reflection.GeneratedProtocolMessageType('RequisicaoAtivacao', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOATIVACAO,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RequisicaoAtivacao)
  })
_sym_db.RegisterMessage(RequisicaoAtivacao)

RespostaAtivacao = _reflection.GeneratedProtocolMessageType('RespostaAtivacao', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTAATIVACAO,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RespostaAtivacao)
  })
_sym_db.RegisterMessage(RespostaAtivacao)

RequisicaoTermino = _reflection.GeneratedProtocolMessageType('RequisicaoTermino', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOTERMINO,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RequisicaoTermino)
  })
_sym_db.RegisterMessage(RequisicaoTermino)

RespostaTermino = _reflection.GeneratedProtocolMessageType('RespostaTermino', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTATERMINO,
  '__module__' : 'server_pares_pb2'
  # @@protoc_insertion_point(class_scope:RespostaTermino)
  })
_sym_db.RegisterMessage(RespostaTermino)



_SERVERPARES = _descriptor.ServiceDescriptor(
  name='ServerPares',
  full_name='ServerPares',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=318,
  serialized_end=539,
  methods=[
  _descriptor.MethodDescriptor(
    name='Insere',
    full_name='ServerPares.Insere',
    index=0,
    containing_service=None,
    input_type=_REQUISICAOINSERCAO,
    output_type=_RESPOSTAINSERCAO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Consulta',
    full_name='ServerPares.Consulta',
    index=1,
    containing_service=None,
    input_type=_REQUISICAOCONSULTA,
    output_type=_RESPOSTACONSULTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Ativa',
    full_name='ServerPares.Ativa',
    index=2,
    containing_service=None,
    input_type=_REQUISICAOATIVACAO,
    output_type=_RESPOSTAATIVACAO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Termina',
    full_name='ServerPares.Termina',
    index=3,
    containing_service=None,
    input_type=_REQUISICAOTERMINO,
    output_type=_RESPOSTATERMINO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERPARES)

DESCRIPTOR.services_by_name['ServerPares'] = _SERVERPARES

# @@protoc_insertion_point(module_scope)
